export type TransactionType = "receita" | "despesa";
export type PaymentMethod  = "dinheiro" | "débito" | "crédito";
export type BillType       = "fixa" | "variavel" | "divida" | "cartao";

export interface Transaction {
  id:            string;
  type:          TransactionType;
  amount:        number;
  category:      string;
  description:   string;
  date:          string;           // ISO date (YYYY-MM-DD)
  paymentMethod?: PaymentMethod;
  creditCardId?:  string;
  autoGenerated?: boolean;         // gerada ao marcar conta como paga
  sourceBillId?:  string;
}

export interface CardSubTx {
  description: string;
  amount:      number;
  date?:       string;
}

export interface Bill {
  id:        string;
  name:      string;
  amount:    number;
  dueDate:   string;               // ISO
  paid:      boolean;
  paidAt?:   string;
  category:  string;
  billType:  BillType;
  recurring: boolean;
  // dívidas
  interestRate?:    number;        // % ao mês
  negotiation?:     string;
  originalDueDate?: string;
  // cartões
  cardLimit?: number;
  closingDay?: number;             // 1-31
  dueDay?:    number;              // 1-31
  transactions?: CardSubTx[];
}

export interface AdvisorMessage {
  role:    "user" | "assistant";
  content: string;
}

export type AiPersonality = "direto" | "engracado" | "durao" | "formal";
export type ColorTheme = "purple" | "cyan" | "emerald" | "rose" | "amber" | "sunset" | "ocean" | "monochrome";

/** Categoria especial: despesas aqui alimentam a Reserva de Emergência. */
export const RESERVE_CATEGORY = "Reserva de Emergência";
/** Categoria especial: aportes em sonhos (gerados pela aba Sonhos). */
export const DREAM_CATEGORY = "Sonhos";

/** Categorias tratadas como "despesas fixas recorrentes" para meta de reserva. */
export const FIXED_EXPENSE_CATEGORIES = ["Moradia", "Casa", "Serviços", "Transporte", "Educação", "Saúde"];

export interface Settings {
  userName:                  string;
  expectedIncome:            number;
  monthStartDay:             number;
  minBalanceAlert:           number;
  customIncomeCategories:    string[];
  customExpenseCategories:   string[];
  emergencyReserveSaved:     number;
  /** Multiplicador de meses de reserva (padrão 6). */
  emergencyMonthsGoal?:      number;
  /** Meta customizada em R$; se definida, sobrescreve o cálculo automático. */
  emergencyCustomGoal?:      number | null;
  aiPersonality:             AiPersonality;
  colorTheme:                ColorTheme;
  /** Papel de parede animado ("RikuAI Worlds") na Home. */
  liveWallpaper?:            boolean;
  /** Simulação local ("Simular Premium") — a verdade real vem do useIsPremium. */
  isPremium:                 boolean;
  /** Preferências de notificação (locais). */
  notifyBills?:               boolean;
  notifyGoals?:               boolean;
  notifyDreams?:              boolean;
  notifySystem?:              boolean;
}

export interface FinanceState {
  transactions:    Transaction[];
  bills:           Bill[];
  initialBalance:  number;
  settings:        Settings;
  welcomeShown:    boolean;
  advisorMessages: AdvisorMessage[];
}
