// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-workspaces.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_workspaces_default = defineTool({
  name: "list_workspaces",
  title: "Listar workspaces",
  description: "Lista os workspaces (ex.: Pessoal, Yakin Box) aos quais o usu\xE1rio autenticado tem acesso.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("workspaces").select("id, name, owner_id").order("created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { workspaces: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "Listar transa\xE7\xF5es",
  description: "Lista transa\xE7\xF5es (receitas e despesas) do usu\xE1rio autenticado, opcionalmente filtradas por workspace e intervalo de datas.",
  inputSchema: {
    workspace_id: z.string().uuid().optional().describe("ID do workspace (opcional; se omitido, retorna de todos os workspaces do usu\xE1rio)."),
    from: z.string().optional().describe("Data inicial ISO (YYYY-MM-DD)."),
    to: z.string().optional().describe("Data final ISO (YYYY-MM-DD)."),
    limit: z.number().int().min(1).max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    let q = supabaseForUser2(ctx).from("transactions").select("*").order("date", { ascending: false }).limit(limit ?? 100);
    if (workspace_id) q = q.eq("workspace_id", workspace_id);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-bills.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bills_default = defineTool3({
  name: "list_bills",
  title: "Listar contas",
  description: "Lista as contas (fixas, d\xEDvidas, cart\xF5es) do usu\xE1rio autenticado, com filtro opcional por workspace e status de pagamento.",
  inputSchema: {
    workspace_id: z2.string().uuid().optional(),
    only_unpaid: z2.boolean().optional().describe("Se true, retorna apenas contas n\xE3o pagas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, only_unpaid }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    let q = supabaseForUser3(ctx).from("bills").select("*").order("due_date", { ascending: true });
    if (workspace_id) q = q.eq("workspace_id", workspace_id);
    if (only_unpaid) q = q.eq("is_paid", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { bills: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_transaction_default = defineTool4({
  name: "create_transaction",
  title: "Registrar transa\xE7\xE3o",
  description: "Cria uma nova transa\xE7\xE3o (receita ou despesa) em um workspace do usu\xE1rio.",
  inputSchema: {
    workspace_id: z3.string().uuid().describe("Workspace onde criar a transa\xE7\xE3o."),
    type: z3.enum(["income", "expense"]).describe("Tipo: income (receita) ou expense (despesa)."),
    amount: z3.number().positive().describe("Valor em BRL (positivo)."),
    category: z3.string().min(1).describe("Categoria (ex.: Alimenta\xE7\xE3o, Moradia, Sal\xE1rio)."),
    description: z3.string().optional(),
    date: z3.string().describe("Data ISO YYYY-MM-DD."),
    payment_method: z3.enum(["dinheiro", "d\xE9bito", "cr\xE9dito"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    const { data, error } = await supabaseForUser4(ctx).from("transactions").insert({
      workspace_id: input.workspace_id,
      type: input.type,
      amount: input.amount,
      category: input.category,
      description: input.description ?? null,
      date: input.date,
      payment_method: input.payment_method ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Transa\xE7\xE3o criada: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tenlgnxpwleqdbcqmysl";
var mcp_default = defineMcp({
  name: "riku-ai-mcp",
  title: "Riku AI \u2014 Finan\xE7as",
  version: "0.1.0",
  instructions: "Ferramentas para o app Riku AI (controle financeiro pessoal em BRL). Use `list_workspaces` para descobrir os workspaces do usu\xE1rio, `list_transactions` e `list_bills` para ler dados, e `create_transaction` para registrar receitas/despesas. Todos os valores s\xE3o em Reais (BRL). Datas em ISO YYYY-MM-DD.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_workspaces_default, list_transactions_default, list_bills_default, create_transaction_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
